overrides:
  "@wallet-standard/ui-features": "1.0.1"
  "@wallet-standard/ui-registry": "1.0.1"

onlyBuiltDependencies:
  - "@solana/web3.js"

allowBuilds:
  '@reown/appkit': true
  bigint-buffer: true
  bufferutil: true
  esbuild: true
  keccak: true
  sharp: true
  utf-8-validate: true
