import type {
  Agent,
  Market,
  NewsContext,
  Position,
  TradeEvent,
  TradeIdea,
  VisualTrace,
  WatchlistItem,
} from "./arena-types";

export const agents: Agent[] = [
  {
    id: "fibonacci-trend",
    name: "Auron",
    strategyLabel: "Fibonacci trend continuation",
    status: "monitoring",
    primaryMarket: "XAU/USD",
    timeframe: "15m",
    winRate: 61,
    pnlPercent: 8.4,
    openPositions: 1,
    score: 1240,
    lastAction: "Monitoring long after second candle check.",
  },
  {
    id: "third-touch",
    name: "Kairos",
    strategyLabel: "Third touch trendline",
    status: "watchlist",
    primaryMarket: "XAG/USD",
    timeframe: "1h",
    winRate: 57,
    pnlPercent: 5.9,
    openPositions: 0,
    score: 1118,
    lastAction: "Watchlist active while price approaches projected touch.",
  },
];

export const markets: Market[] = [
  {
    symbol: "XAU/USD",
    displayName: "Gold",
    assetClass: "commodity",
    price: 2334.82,
    changePercent: 0.72,
    dailyRange: "2320.10 - 2341.60",
    sessionBias: "bullish",
  },
  {
    symbol: "XAG/USD",
    displayName: "Silver",
    assetClass: "commodity",
    price: 27.44,
    changePercent: -0.18,
    dailyRange: "27.18 - 27.61",
    sessionBias: "mixed",
  },
  {
    symbol: "EUR/USD",
    displayName: "Euro / US Dollar",
    assetClass: "forex",
    price: 1.0714,
    changePercent: 0.11,
    dailyRange: "1.0688 - 1.0726",
    sessionBias: "mixed",
  },
  {
    symbol: "GBP/USD",
    displayName: "Pound / US Dollar",
    assetClass: "forex",
    price: 1.2734,
    changePercent: 0.08,
    dailyRange: "1.2698 - 1.2751",
    sessionBias: "mixed",
  },
  {
    symbol: "USD/JPY",
    displayName: "US Dollar / Yen",
    assetClass: "forex",
    price: 153.42,
    changePercent: -0.14,
    dailyRange: "152.88 - 153.74",
    sessionBias: "mixed",
  },
  {
    symbol: "Volatility 10 Index",
    displayName: "Volatility 10 Index",
    assetClass: "synthetic",
    price: 9842.3,
    changePercent: 0.22,
    dailyRange: "9710.0 - 9890.0",
    sessionBias: "mixed",
  },
  {
    symbol: "Volatility 25 Index",
    displayName: "Volatility 25 Index",
    assetClass: "synthetic",
    price: 34182.6,
    changePercent: -0.41,
    dailyRange: "33640.0 - 34520.0",
    sessionBias: "mixed",
  },
  {
    symbol: "Volatility 75 Index",
    displayName: "Volatility 75 Index",
    assetClass: "synthetic",
    price: 102340.5,
    changePercent: 0.67,
    dailyRange: "101200.0 - 103100.0",
    sessionBias: "bullish",
  },
  {
    symbol: "Crash 1000 Index",
    displayName: "Crash 1000 Index",
    assetClass: "synthetic",
    price: 8120.44,
    changePercent: -0.09,
    dailyRange: "8040.0 - 8180.0",
    sessionBias: "mixed",
  },
  {
    symbol: "Boom 500 Index",
    displayName: "Boom 500 Index",
    assetClass: "synthetic",
    price: 19874.2,
    changePercent: 0.31,
    dailyRange: "19640.0 - 20010.0",
    sessionBias: "bullish",
  },
  {
    symbol: "Volatility 15 (1s) Index",
    displayName: "Volatility 15 (1s) Index",
    assetClass: "synthetic",
    price: 13096.4,
    changePercent: -0.84,
    dailyRange: "12220.0 - 13512.0",
    sessionBias: "mixed",
  },
];

export const newsContexts: NewsContext[] = [
  {
    id: "news-1",
    marketSymbol: "XAU/USD",
    headline: "Dollar softens ahead of US data window",
    state: "supportive",
    sourceLabel: "Macro desk",
    publishedAt: "12m ago",
    note: "Supports current long bias but does not replace entry confirmation.",
  },
  {
    id: "news-2",
    marketSymbol: "XAG/USD",
    headline: "No major catalyst in current session",
    state: "neutral",
    sourceLabel: "Market pulse",
    publishedAt: "28m ago",
    note: "Technical setup remains valid without strong headline influence.",
  },
  {
    id: "news-3",
    marketSymbol: "EUR/USD",
    headline: "Speakers scheduled later in New York overlap",
    state: "risk",
    sourceLabel: "Calendar risk",
    publishedAt: "41m ago",
    note: "High-impact commentary could delay entries on this pair.",
  },
];

export const watchlistItems: WatchlistItem[] = [
  // ── Auron (fibonacci-trend) — 6 markets ──────────────────────────────────
  {
    id: "watch-au-1",
    agentId: "fibonacci-trend",
    marketSymbol: "XAG/USD",
    setupLabel: "Silver impulse leg — watching for retracement",
    timeframe: "15m",
    status: "watching",
    triggerNote: "Fib leg not yet confirmed. Waiting for impulse close.",
    confluenceState: "neutral",
  },
  {
    id: "watch-au-2",
    agentId: "fibonacci-trend",
    marketSymbol: "EUR/USD",
    setupLabel: "Retracement into premium discount band",
    timeframe: "15m",
    status: "armed",
    triggerNote: "News risk is elevated, hold until post-event volatility settles.",
    confluenceState: "risk",
  },
  {
    id: "watch-au-3",
    agentId: "fibonacci-trend",
    marketSymbol: "GBP/USD",
    setupLabel: "Cable impulse — monitoring 0.618 zone",
    timeframe: "15m",
    status: "watching",
    triggerNote: "Structural low intact. Entry requires confirmed bounce candle.",
    confluenceState: "neutral",
  },
  {
    id: "watch-au-4",
    agentId: "fibonacci-trend",
    marketSymbol: "Volatility 75 Index",
    setupLabel: "V75 trend leg — high-momentum fib continuation",
    timeframe: "15m",
    status: "watching",
    triggerNote: "Use for weekend coverage and high-volatility session testing.",
    confluenceState: "neutral",
  },
  {
    id: "watch-au-5",
    agentId: "fibonacci-trend",
    marketSymbol: "Volatility 25 Index",
    setupLabel: "V25 retracement — balanced volatility leg",
    timeframe: "15m",
    status: "watching",
    triggerNote: "Cleaner fib structure than V75. Preferred for precision entries.",
    confluenceState: "neutral",
  },
  // ── Kairos (third-touch) — 6 markets ─────────────────────────────────────
  {
    id: "watch-ka-1",
    agentId: "third-touch",
    marketSymbol: "XAU/USD",
    setupLabel: "Gold descending line — approaching third contact",
    timeframe: "1h",
    status: "watching",
    triggerNote: "Projected touch within 1–2 sessions. Rejection wick needed.",
    confluenceState: "neutral",
  },
  {
    id: "watch-ka-2",
    agentId: "third-touch",
    marketSymbol: "EUR/USD",
    setupLabel: "Euro ascending trendline — third touch formation",
    timeframe: "1h",
    status: "watching",
    triggerNote: "Line integrity intact. Entry on confirmed break-and-retest.",
    confluenceState: "neutral",
  },
  {
    id: "watch-ka-3",
    agentId: "third-touch",
    marketSymbol: "GBP/USD",
    setupLabel: "Cable — descending channel third touch",
    timeframe: "1h",
    status: "watching",
    triggerNote: "Watching for compression wick into resistance shelf.",
    confluenceState: "neutral",
  },
  {
    id: "watch-ka-4",
    agentId: "third-touch",
    marketSymbol: "Volatility 10 Index",
    setupLabel: "V10 range trendline — low-noise structure",
    timeframe: "1h",
    status: "watching",
    triggerNote: "Lower volatility makes trendline structure cleaner. Good test case.",
    confluenceState: "neutral",
  },
  {
    id: "watch-ka-5",
    agentId: "third-touch",
    marketSymbol: "Crash 1000 Index",
    setupLabel: "Crash 1000 — spike-and-recover trendline test",
    timeframe: "1h",
    status: "watching",
    triggerNote: "Crash events form natural touch anchors. Third touch near resistance shelf.",
    confluenceState: "neutral",
  },
];

export const tradeIdeas: TradeIdea[] = [
  {
    id: "idea-1",
    agentId: "fibonacci-trend",
    marketSymbol: "XAU/USD",
    direction: "long",
    status: "entered",
    entry: 2330.4,
    stopLoss: 2323.8,
    takeProfit: 2349.6,
    confidence: 0.82,
    confluenceState: "supportive",
    thesis:
      "Structure remains intact after retracement into fib zone with bullish follow-through.",
  },
  {
    id: "idea-2",
    agentId: "third-touch",
    marketSymbol: "XAG/USD",
    direction: "short",
    status: "watchlist",
    entry: 27.58,
    stopLoss: 27.76,
    takeProfit: 27.14,
    confidence: 0.64,
    confluenceState: "neutral",
    thesis:
      "Trendline reaction is developing, but entry waits on a cleaner touch and close.",
  },
];

export const positions: Position[] = [
  {
    id: "position-1",
    agentId: "fibonacci-trend",
    marketSymbol: "XAU/USD",
    direction: "long",
    timeframe: "15m",
    entry: 2330.4,
    markPrice: 2337.9,
    stopLoss: 2323.8,
    takeProfit: 2349.6,
    pnlPercent: 0.32,
    progressLabel: "38% to take profit",
    nextCheckIn: "in 9m",
  },
];

export const tradeEvents: TradeEvent[] = [
  {
    id: "event-1",
    agentId: "fibonacci-trend",
    marketSymbol: "XAU/USD",
    timestamp: "09:12",
    title: "Watchlist armed",
    detail: "Retracement reached the 0.618 zone with market structure preserved.",
    stage: "ready",
  },
  {
    id: "event-2",
    agentId: "fibonacci-trend",
    marketSymbol: "XAU/USD",
    timestamp: "09:28",
    title: "Entry marked",
    detail: "Bullish confirmation candle closed above the trigger level.",
    stage: "entered",
  },
  {
    id: "event-3",
    agentId: "fibonacci-trend",
    marketSymbol: "XAU/USD",
    timestamp: "09:58",
    title: "Monitoring cycle",
    detail: "Second 15m candle completed. Position remains within thesis.",
    stage: "monitoring",
  },
  {
    id: "event-4",
    agentId: "third-touch",
    marketSymbol: "XAG/USD",
    timestamp: "10:04",
    title: "Trendline projected",
    detail: "Touch one and two locked. Price is approaching the reaction zone.",
    stage: "watchlist",
  },
];

export const visualTraces: VisualTrace[] = [
  {
    id: "trace-1",
    agentId: "fibonacci-trend",
    marketSymbol: "XAU/USD",
    timeframe: "15m",
    updatedAt: "Updated 2m ago",
    annotations: [
      {
        id: "annotation-1",
        type: "fibonacci",
        label: "Retracement mapped",
        detail: "Swing low to swing high is locked for the current continuation leg.",
        revealStep: 1,
        geometry: {
          kind: "fibonacci",
          startBarIndex: 34,
          endBarIndex: 48,
          highPrice: 2341.4,
          lowPrice: 2324.8,
          levels: [0, 0.5, 0.618, 0.7, 1],
        },
      },
      {
        id: "annotation-2",
        type: "zone",
        label: "0.618 reaction zone",
        detail: "Entry interest held after the first bullish response inside the zone.",
        revealStep: 1,
        geometry: {
          kind: "zone",
          startBarIndex: 35,
          endBarIndex: 48,
          highPrice: 2332.4,
          lowPrice: 2329.1,
          tone: "zone",
        },
      },
      {
        id: "annotation-3",
        type: "entry",
        label: "Long trigger marked",
        detail: "Confirmation candle close converted the idea into an entered trade.",
        revealStep: 2,
        geometry: {
          kind: "marker",
          position: { barIndex: 39, price: 2330.4 },
          text: "Entry",
          tone: "entry",
        },
      },
      {
        id: "annotation-3b",
        type: "stop-loss",
        label: "Risk line held below structure",
        detail: "Stop remains below the retracement zone and protected swing point.",
        revealStep: 2,
        geometry: {
          kind: "marker",
          position: { barIndex: 28, price: 2323.8 },
          text: "SL",
          tone: "stop",
        },
      },
      {
        id: "annotation-4",
        type: "take-profit",
        label: "Target extension",
        detail: "Take profit aligned with prior impulse expansion and session range ceiling.",
        revealStep: 3,
        geometry: {
          kind: "marker",
          position: { barIndex: 67, price: 2349.6 },
          text: "TP",
          tone: "target",
        },
      },
      {
        id: "annotation-4b",
        type: "trendline",
        label: "Impulse guide",
        detail: "Continuation line keeps the current bullish structure readable.",
        revealStep: 3,
        geometry: {
          kind: "line",
          start: { barIndex: 8, price: 2326.8 },
          end: { barIndex: 51, price: 2334.8 },
          tone: "default",
        },
      },
    ],
  },
  {
    id: "trace-2",
    agentId: "third-touch",
    marketSymbol: "XAG/USD",
    timeframe: "1h",
    updatedAt: "Updated 5m ago",
    annotations: [
      {
        id: "annotation-5",
        type: "trendline",
        label: "Descending line anchored",
        detail: "Touch one and touch two are fixed for projected third-touch logic.",
        revealStep: 1,
        geometry: {
          kind: "line",
          start: { barIndex: 12, price: 27.66 },
          end: { barIndex: 55, price: 27.42 },
          tone: "default",
        },
      },
      {
        id: "annotation-6",
        type: "zone",
        label: "Reaction pocket",
        detail: "Price needs to reject here before the watchlist advances to ready.",
        revealStep: 2,
        geometry: {
          kind: "zone",
          startBarIndex: 48,
          endBarIndex: 60,
          highPrice: 27.53,
          lowPrice: 27.38,
          tone: "zone",
        },
      },
      {
        id: "annotation-7",
        type: "entry",
        label: "Projected trigger",
        detail: "If rejection completes here, the short trigger becomes valid.",
        revealStep: 3,
        geometry: {
          kind: "marker",
          position: { barIndex: 54, price: 27.46 },
          text: "Entry",
          tone: "entry",
        },
      },
    ],
  },
];
